apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: httpd-deploy
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata: 
        labels:
          app: myapp
    spec:
      containers:
        - name: httpd
          image: httpd:2.4.28
          ports:
            - containerPort: 80