apiVersion: v1
kind: Service
metadata:
  name: httpd-service-nautilus
  namespace: httpd-namespace-nautilus
  labels:
    app: httpd
spec:
  selector:
    app: httpd
  type: NodePort
  ports:
    - port: 80
      nodePort: 30004