- name: Create link
  hosts: all
  become: true
  tasks:
    - name: create blank file
      file:
        path: /opt/devops/blog.txt
        state: touch
        owner: tony
        group: tony
      when: inventory_hostname == "stapp01"
    - name: create blank file
      file:
        path: /opt/devops/story.txt
        state: touch
        owner: steve
        group: steve
      when: inventory_hostname == "stapp02"
    - name: create blank file
      file:
        path: /opt/devops/media.txt
        state: touch
        owner: banner
        group: banner
      when: inventory_hostname == "stapp03"
    - name: create symbolic link
      file:
        src: /opt/devops
        dest: /var/www/html
        state: link