apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-devops
  namespace: tomcat-namespace-devops
  labels:
    app: tomcat
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
  - port: 8080
    nodePort: 32227
