apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  MYSQL_HOST: mysql-service
  MYSQL_PASSWORD: password 
  MYSQL_USER: joey
  MYSQL_DATABASE: kodekloud
  MYSQL_ROOT_PASSWORD: password