apiVersion: v1
kind: Pod
metadata:
  name: volume-share-devops
spec:
  containers:
    - name: volume-container-devops-1
      image: centos:latest
      command:
        - "/bin/bash"
        - "-c"
        - "sleep 100"
      volumeMounts:
        - mountPath: /tmp/ecommerce
          name: volume-share
    - name: volume-container-devops-2
      image: centos:latest
      command:
        - "/bin/bash"
        - "-c"
        - "sleep 100"
      volumeMounts:
        - mountPath: /tmp/apps
          name: volume-share
  volumes:
    - name: volume-share
      emptyDir:
        sizeLimit: 500Mi